/**
 * watsonxAssistant.js
 * Demo implementation: context-aware responses using hardcoded employee
 * profile data. Structured to mimic a RAG + LLM pipeline — in production
 * this context object would be fetched from Firestore and the response
 * generated by IBM Granite via the watsonx.ai API.
 */

// ─── Hardcoded employee context (demo) ───────────────────────────────────────
// In production: fetched per-user from Firestore employees/{uid}, users/{uid},
// documents, checklists, tasks, and accessRequests collections.
const EMPLOYEE_CONTEXT = {
  name:            'Aanya Sharma',
  email:           'aanya.sharma@ibm.com',
  designation:     'Associate Software Engineer',
  department:      'Software Engineering',
  joiningDate:     'July 15, 2025',
  location:        'IBM India, Bengaluru — Manyata Tech Park, Tower B, 4th Floor',
  manager:         'Rajesh Mehta',
  managerEmail:    'rajesh.mehta@ibm.com',
  buddy:           'Priya Nair',
  buddyEmail:      'priya.nair@ibm.com',
  hr:              'Sunita Khanna',
  hrEmail:         'sunita.khanna@ibm.com',
  hrPhone:         '+91-80-4920-1234',
  os:              'Mac',
  onboardingStage: 'in_progress',
  pendingDocs:     ['Identity Proof', 'Education Certificate', 'Signed Offer Letter'],
  pendingTasks:    ['Complete W3ID setup', 'Submit onboarding documents', 'Accept offer letter', 'Request GitHub Enterprise access'],
  benefits:        'Health, Dental, Vision insurance + IBM Stock Purchase Plan. Enroll within 30 days of joining via the HR benefits portal.',
  reportingTime:   '9:00 AM IST on your joining date. Carry a government-issued photo ID for gate entry.',
};

// ─── Intent → response map ────────────────────────────────────────────────────
// Each entry has:
//   keywords  — any of these appearing in the message triggers this intent
//   response  — a function that takes the context and returns a rich string
const INTENTS = [
  {
    keywords: ['joining date', 'join date', 'start date', 'when do i start', 'when do i join', 'first day', 'day one', 'day 1'],
    response: (ctx) =>
      `Your official joining date is **${ctx.joiningDate}**.\n\nYou're expected to report to the ${ctx.location} at ${ctx.reportingTime}\n\nMake sure all your onboarding documents are submitted before that date so IT can have your system ready on Day 1. If you need to reschedule, reach out to your HR contact ${ctx.hr} at ${ctx.hrEmail}.`,
  },
  {
    keywords: ['manager', 'reporting to', 'report to', 'who is my boss', 'my lead', 'supervisor'],
    response: (ctx) =>
      `Your reporting manager is **${ctx.manager}** (${ctx.managerEmail}).\n\n${ctx.manager} leads the ${ctx.department} team and will be your primary point of contact for project assignments, performance reviews, and day-to-day guidance. I'd recommend sending them a quick introduction email before your joining date — it goes a long way!`,
  },
  {
    keywords: ['buddy', 'onboarding buddy', 'peer buddy', 'who is my buddy'],
    response: (ctx) =>
      `Your onboarding buddy is **${ctx.buddy}** (${ctx.buddyEmail}).\n\n${ctx.buddy} is a fellow IBMer who will help you navigate your first few weeks — from finding your way around the office to understanding team culture and internal tools. Don't hesitate to reach out to them for anything, big or small!`,
  },
  {
    keywords: ['manager and buddy', 'buddy and manager', 'who are my contacts', 'team contacts', 'who should i contact'],
    response: (ctx) =>
      `Here are your key onboarding contacts:\n\n👤 **Manager:** ${ctx.manager} — ${ctx.managerEmail}\n🤝 **Buddy:** ${ctx.buddy} — ${ctx.buddyEmail}\n🏢 **HR:** ${ctx.hr} — ${ctx.hrEmail}\n\nYour manager handles your work assignments and career goals, your buddy helps you settle in socially and culturally, and HR is your go-to for any administrative or benefits queries.`,
  },
  {
    keywords: ['location', 'office', 'where is my office', 'job location', 'where do i work', 'office address', 'which city', 'bangalore', 'bengaluru'],
    response: (ctx) =>
      `Your work location is **${ctx.location}**.\n\nBengaluru is IBM India's largest engineering hub. The Manyata Tech Park campus has a cafeteria, gym, and dedicated onboarding desk on the ground floor of Tower B. On your first day, head to the reception and ask for the HR onboarding team — they'll get you badged in and set up.`,
  },
  {
    keywords: ['hr', 'human resources', 'hr contact', 'hr name', 'who is hr', 'hr email', 'hr phone', 'hr number'],
    response: (ctx) =>
      `Your HR Business Partner is **${ctx.hr}**.\n\n📧 Email: ${ctx.hrEmail}\n📞 Phone: ${ctx.hrPhone}\n\n${ctx.hr} is your point of contact for offer-related queries, benefits enrollment, background verification status, and any administrative concerns during your onboarding. She's available Monday–Friday, 9 AM–6 PM IST.`,
  },
  {
    keywords: ['document', 'upload', 'what documents', 'documents needed', 'pending documents', 'which documents', 'submit document'],
    response: (ctx) =>
      `You currently have **${ctx.pendingDocs.length} documents** pending submission:\n\n${ctx.pendingDocs.map((d, i) => `${i + 1}. ${d}`).join('\n')}\n\nHead to the **Documents** section in the sidebar to upload them. Accepted formats are PDF, JPG, and PNG. All documents go through an admin verification step — you'll be notified once each one is approved.`,
  },
  {
    keywords: ['task', 'pending task', 'what to do', 'what should i do', 'next step', 'todo', 'checklist'],
    response: (ctx) =>
      `Here are your current pending onboarding tasks:\n\n${ctx.pendingTasks.map((t, i) => `${i + 1}. ${t}`).join('\n')}\n\nI'd recommend starting with your **W3ID setup** — it unlocks access to all IBM internal systems. Your full checklist is available in the **Checklist** section on the sidebar, where you can track and mark tasks as complete.`,
  },
  {
    keywords: ['w3id', 'ibm id', 'intranet', 'w3', 'ibm login', 'credentials', 'ibm account'],
    response: (ctx) =>
      `Your **W3ID** is your IBM global identity — it gives you access to the intranet, internal tools, IBM Learning, and all enterprise systems.\n\nYou'll receive a W3ID setup email from IBM IT on or before your joining date (${ctx.joiningDate}). Complete the setup within **48 hours** of receiving it. If you don't get the email, contact ${ctx.hr} at ${ctx.hrEmail} and she'll escalate it to IT.`,
  },
  {
    keywords: ['laptop', 'mac', 'macbook', 'computer', 'device', 'hardware', 'system setup', 'mac setup'],
    response: (ctx) =>
      `You've selected **${ctx.os}** as your preferred OS, so you'll be issued a MacBook Pro.\n\nOn Day 1, IT will hand over your device with IBM's baseline security profile pre-installed. Here's a quick setup checklist:\n\n1. Sign in with your W3ID\n2. Enable FileVault disk encryption (required by IBM policy)\n3. Install IBM Verify for MFA\n4. Connect to the IBM VPN (Cisco AnyConnect)\n5. Set up IBM Outlook for email\n\nThe **Setup Guide** section in the portal has detailed step-by-step instructions.`,
  },
  {
    keywords: ['benefit', 'insurance', 'health', 'medical', 'dental', 'vision', 'stock', 'perk'],
    response: (ctx) =>
      `IBM offers a comprehensive benefits package for you:\n\n${ctx.benefits}\n\n⚠️ Benefits enrollment must be completed within **30 days** of your joining date (${ctx.joiningDate}). Log in to the IBM HR portal with your W3ID to enroll. Contact ${ctx.hr} at ${ctx.hrEmail} if you have any trouble accessing the portal.`,
  },
  {
    keywords: ['designation', 'role', 'title', 'job title', 'position', 'my role'],
    response: (ctx) =>
      `Your designation at IBM is **${ctx.designation}** within the **${ctx.department}** team.\n\nAs an ASE, you'll work on real engineering projects from Day 1 alongside your manager ${ctx.manager} and a wider team of engineers. Your growth path typically follows ASE → SE → SSE → Advisory Engineer, with IBM's structured mentoring and L&D programs supporting your progression.`,
  },
  {
    keywords: ['department', 'team', 'which team', 'my team', 'which department'],
    response: (ctx) =>
      `You're joining the **${ctx.department}** department.\n\nYour manager is ${ctx.manager} and your onboarding buddy ${ctx.buddy} is also part of this team, so you'll have great support from Day 1. The team is based at ${ctx.location}.`,
  },
  {
    keywords: ['access', 'github', 'jira', 'confluence', 'slack', 'tool', 'application access', 'request access', 'software'],
    response: (ctx) =>
      `You can request access to tools like GitHub Enterprise, Jira, Confluence, and IBM Cloud via the **Access Requests** section in the sidebar.\n\nApprovals are handled by your manager (${ctx.manager}) and typically take **1–2 business days**. GitHub Enterprise access is especially important for the ${ctx.department} team — I'd recommend submitting that request on Day 1.`,
  },
  {
    keywords: ['report', 'reporting time', 'what time', 'when to arrive', 'arrive', 'time to come'],
    response: (ctx) =>
      `You're expected to arrive at **${ctx.reportingTime}** on ${ctx.joiningDate}.\n\nHead to ${ctx.location} — the HR onboarding team will be at the ground floor reception to receive new joiners. Carry a government-issued photo ID (Aadhaar, Passport, or Driver's License) for security verification and badge creation.`,
  },
  {
    keywords: ['hello', 'hi', 'hey', 'good morning', 'good afternoon', 'good evening', 'howdy'],
    response: (ctx) =>
      `Hello ${ctx.name}! 👋 I'm your IBM Onboarding Assistant, powered by watsonx.\n\nI have full context of your onboarding profile and I'm here to help you with anything — your joining date, manager details, office location, pending documents, IT setup, and more.\n\nWhat would you like to know?`,
  },
  {
    keywords: ['help', 'what can you do', 'what can you answer', 'what do you know', 'capabilities'],
    response: (ctx) =>
      `I'm your personalized IBM Onboarding Assistant and I have access to your complete onboarding profile. Here's what I can help you with:\n\n📅 Joining date & reporting time\n👤 Manager & buddy details\n📍 Office location\n📋 Pending tasks & checklist\n📄 Required documents\n🏥 Benefits & insurance\n💻 Laptop & IT setup\n🔐 W3ID & access requests\n👩‍💼 HR contact details\n\nJust ask me anything — I'm here to make your onboarding as smooth as possible!`,
  },
  {
    keywords: ['background', 'bgv', 'background verification', 'background check'],
    response: (ctx) =>
      `Your Background Verification (BGV) is typically initiated by IBM's third-party partner (KPMG) within 2–3 days of your offer acceptance.\n\nYou'll receive an email with a link to submit your documents for BGV. Make sure your employment history, education certificates, and address proof are accurate. If you have any BGV-related concerns, contact ${ctx.hr} at ${ctx.hrEmail}.`,
  },
  {
    keywords: ['offer', 'offer letter', 'accept offer', 'sign offer'],
    response: (ctx) =>
      `Your offer letter is available in the **Documents** section of this portal. Once you've reviewed all the terms and conditions, click **Accept Offer** to formally confirm your joining.\n\nAccepting the offer will move your onboarding status to "In Progress" and unlock the full checklist and IT setup flows. Your joining date remains **${ctx.joiningDate}**.`,
  },
];

// ─── Main function ────────────────────────────────────────────────────────────
async function askAssistant(message) {
  // Simulate LLM inference latency (600–1100ms)
  await new Promise((resolve) => setTimeout(resolve, 600 + Math.random() * 500));

  const lower = (message || '').toLowerCase().trim();

  // Score each intent by counting how many of its keywords appear in the message.
  // Return the highest-scoring match (handles compound questions like "manager and buddy").
  let bestIntent = null;
  let bestScore  = 0;

  for (const intent of INTENTS) {
    const score = intent.keywords.filter((kw) => lower.includes(kw)).length;
    if (score > bestScore) {
      bestScore  = score;
      bestIntent = intent;
    }
  }

  if (bestIntent) {
    // Strip markdown bold markers (**text**) for plain rendering
    const raw = bestIntent.response(EMPLOYEE_CONTEXT);
    return { success: true, response: raw };
  }

  // Graceful fallback
  return {
    success: true,
    response: `I'm your IBM Onboarding Assistant with full context of ${EMPLOYEE_CONTEXT.name}'s profile. I can answer questions about your joining date (${EMPLOYEE_CONTEXT.joiningDate}), manager (${EMPLOYEE_CONTEXT.manager}), office location, pending documents, IT setup, HR contact, and more.\n\nCould you rephrase your question or pick one of the suggested prompts below?`,
  };
}

module.exports = { askAssistant };
